#pragma config(Sensor, in1,    pot,            sensorNone)
#pragma config(Sensor, in2,    gyro,           sensorNone)
#pragma config(Sensor, dgtl5,  encoderleft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderright,   sensorQuadEncoder)
#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           frontright,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           backleft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           backright,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           armleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armright,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           shooter,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition) //competition configuration
#include "Vex_Competition_Includes.c"

#pragma systemFile

void stopDrive() {
	motor[frontleft] = 0;
	motor[frontright] = 0;
	motor[backleft] = 0;
	motor[backright] = 0;
}

void resetSensors() {
	SensorValue[encoderleft] = 0;
	SensorValue[encoderright] = 0;
	SensorValue[gyro] = 0;
}

void pause() {
	wait1Msec(100);
}

void pre_auton() {
	bStopTasksBetweenModes = true;

	stopDrive();
	resetSensors();
	
	
}



void moveForward(float ticks, int speed) {
	SensorValue[encoderleft] = 0;
	SensorValue[encoderright] = 0;

	while (abs(SensorValue[encoderright] / 2 + SensorValue[encoderright] / 2) < ticks) {
		motor[frontleft] = speed;
		motor[frontright] = speed;
		motor[backleft] = speed;
		motor[backright] = speed;
	}

	motor[frontleft] = 0;
	motor[frontright] = 0;
	motor[backleft] = 0;
	motor[backright] = 0;

	pause();
}

void turnRight(int degrees, int speed) {
	int ticks = degrees * 55 / 20;

	SensorValue[encoderright] = 0;

	while (abs(SensorValue[encoderright]) < ticks) {
		motor[frontleft] = speed;
		motor[frontright] = -speed;
		motor[backleft] = speed;
		motor[backright] = -speed;
	}
	
	stopDrive();
	pause();
}

void turnLeft (int degrees, int speed) {
	int ticks = degrees * 51 / 20;

	SensorValue[encoderleft] = 0;

	while (abs(SensorValue[encoderleft]) < ticks) {
		motor[frontleft] = -speed;
		motor[frontright] = speed;
		motor[backleft] = -speed;
		motor[backright] = speed;
	}
	
	stopDrive();
	pause();
}

void arm(bool direction, long time) {
	if (!direction) {
		motor[armleft] = 63;
		motor[armright] = 63;
		wait1Msec(time);
		motor[armleft] = 0;
		motor[armright] = 0;
	} else {
		motor[armleft] = -63;
		motor[armright] = -63;
		wait1Msec(time);
		motor[armleft] = 0;
		motor[armright] = 0;
	}
	
	pause();
}

void flip(long time) {
	motor[claw] = 127;
	wait1Msec(time);
	motor[claw] = 0;
}

void shoot() {
	motor[shooter] = 127;
	wait1Msec(1400);
	motor[shooter] = 0;
}

task autonomous () {
	moveForward(1400, -127);
}

task usercontrol() {
	while (0==0) {
		//Driving with Joysticks
		motor[frontleft] = vexRT[Ch3];
		motor[backleft] = vexRT[Ch3];
		motor[frontright] = vexRT[Ch2];
		motor[backright] = vexRT[Ch2];
/*
		if (vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0 && angle > 1940) {
			motor[armleft] = -127;
			motor[armright] = -127;     //Pressed right foward bumper lifts arm
		} else if (vexRT[Btn6D] == 1 && vexRT[Btn6U] == 0 && angle < 2440) {
			motor[armleft] = 127;
			motor[armright] = 127;     //Pressed right back bumper lowers arm
		} else if ((vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0) || (vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)) {
			motor[armleft] = 0;
			motor[armright] = 0;
		} else {
			motor[armright] = 0;
			motor[armleft] = 0;
		}
		*/
		if (vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0) {
			motor[armleft] = -127;
			motor[armright] = -127;     //Pressed right foward bumper lifts arm
		} else if (vexRT[Btn6D] == 1 && vexRT[Btn6U] == 0) {
			motor[armleft] = 127;
			motor[armright] = 127;     //Pressed right back bumper lowers arm
		} else if ((vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0) || (vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)) {
			motor[armleft] = 0;
			motor[armright] = 0;
		} else {
			motor[armright] = 0;
			motor[armleft] = 0;
		}

		if (vexRT[Btn5U] == 1 && vexRT[Btn5D] == 0) {
			motor[claw] = 55;
		} else if (vexRT[Btn5D] == 1 && vexRT[Btn5U] == 0) {
			motor[claw] = -55;
		} else {
			motor[claw] = 0;
		}

		if (vexRT[Btn8U] == 1 && vexRT[Btn8D] == 0) {
			motor[shooter] = 127;
		} else if (vexRT[Btn8D] == 1 && vexRT[Btn8U] == 0) {
			motor[shooter] = -127;
		} else {
			motor[shooter] = 0;
		}
		
		if (vexRT[Btn7L] == 1 && vexRT[Btn7R] == 0) {
			turnLeft(90, 60);
		} else if (vexRT[Btn7R] == 1 && vexRT[Btn7L] == 0) {
			turnRight(90, 60);
		} else {
		
		}
	}
}
