#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl5,  encoderleft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderright,   sensorQuadEncoder)
#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           frontright,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           backleft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           backright,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           armleft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armright,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           shooter,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition) //competition configuration
#include "Vex_Competition_Includes.c"

#pragma systemFile

int selectedAutonomousColor = 0; //1 is red, 2 is blue, 0 is none
int selectedAutonomousSquare = 0; //1 is close, 2 is far, 0 none
bool skills;

void stopDrive() {
	motor[frontleft] = 0;
	motor[frontright] = 0;
	motor[backleft] = 0;
	motor[backright] = 0;
}

void resetSensors() {
	SensorValue[encoderleft] = 0;
	SensorValue[encoderright] = 0;
	SensorValue[gyro] = 0;
}

void clear() {
	clearLCDLine(0);
	clearLCDLine(1);
}

void pause() {
	wait1Msec(250);
}

void pre_auton() {
	bStopTasksBetweenModes = true;

	clear();

	bLCDBacklight = true;

	string scene = "voltage";
	float voltage = nAvgBatteryLevel;
	string str = "";
	string lastScene = "";

	while (bIfiRobotDisabled) {
		if (lastScene != scene) {
			clear();
		}

		if (scene == "voltage") {
			displayLCDCenteredString(0, "Voltage (mV):");
			displayLCDNumber(1, 0, voltage);
			if (nLCDButtons != 0) {
				scene = "colorSelection";
				wait1Msec(500);
			}
		} else if (scene == "colorSelection") {
			displayLCDCenteredString(0, "1: RED, 2: BLUE");
			displayLCDCenteredString(1, "3: SKILLS/NONE");
			if (nLCDButtons == 1) {
				scene = "redSelection";
				selectedAutonomousColor = 1;
				wait1Msec(500);
			} else if (nLCDButtons == 2) {
				scene = "blueSelection";
				selectedAutonomousColor = 2;
				wait1Msec(500);
			} else if (nLCDButtons == 4) {
				scene = "other";
				wait1Msec(500);
			}
		} else if (scene == "redSelection") {
			displayLCDCenteredString(0, "1: FLAG SIDE");
			displayLCDCenteredString(1, "2: OTHER SIDE");
			if (nLCDButtons == 1) {
				scene = "finished";
				selectedAutonomousSquare = 1;
				wait1Msec(500);
			} else if (nLCDButtons == 2) {
				scene = "finished";
				selectedAutonomousSquare = 2;
			}
		} else if (scene == "blueSelection") {
			displayLCDCenteredString(0, "1: FLAG SIDE");
			displayLCDCenteredString(1, "2: OTHER SIDE");
			if (nLCDButtons == 1) {
				scene = "finished";
				selectedAutonomousSquare = 1;
				wait1Msec(500);
			} else if (nLCDButtons == 2) {
				scene = "finished";
				selectedAutonomousSquare = 2;
			}
		} else if (scene == "finished") {
			if (selectedAutonomousColor == 1) {
				if (selectedAutonomousSquare == 1) {
					displayLCDCenteredString(0, "Selected Auton:");
					displayLCDCenteredString(1, "RED, CLOSE SIDE");
				} else {
					displayLCDCenteredString(0, "Selected Auton:");
					displayLCDCenteredString(1, "RED, FAR SIDE");
				}
			} else if (selectedAutonomousColor == 2) {
				if (selectedAutonomousSquare == 1) {
					displayLCDCenteredString(0, "Selected Auton:");
					displayLCDCenteredString(1, "BLUE, CLOSE SIDE");
				} else {
					displayLCDCenteredString(0, "Selected Auton:");
					displayLCDCenteredString(1, "BLUE, FAR SIDE");
				}
			} else if (selectedAutonomousColor == 0 && selectedAutonomousSquare == 0) {
				displayLCDCenteredString(0, "Selected auton:");
				displayLCDCenteredString(1, "NONE");
			} else {
				displayLCDCenteredString(0, "Selected auton:");
				displayLCDCenteredString(1, "SKILLS");
			}
		} else if (scene == "other") {
			displayLCDCenteredString(0, "1: NO AUTON");
			displayLCDCenteredString(1, "2: SKILLS");
			if (nLCDButtons == 1) {
				scene = "finished";
				selectedAutonomousColor = 0;
				selectedAutonomousSquare = 0;
				wait1Msec(500);
			} else if (nLCDButtons == 2) {
				scene = "finished";
				skills = true;
				selectedAutonomousSquare = 3;
				selectedAutonomousColor = 3;
			}
		} else {
			displayLCDCenteredString(0, "ERROR: Failed");
			displayLCDCenteredString(1, "to match scenes");
		}
		lastScene = scene;

	}

	stopDrive();
	resetSensors();

	bLCDBacklight = false;

}

/*ticks must be positive, speed can be different values*/

void moveBackward(float ticks, int speed) {
	SensorValue[encoderleft] = 0;
	SensorValue[encoderright] = 0;

	int error = SensorValue[encoderleft] - SensorValue[encoderright];
	int lastError;
	int derivative;

	float kp = 3;
	float kd = 0;

	int leftspeed = speed;
	int rightspeed = speed;

	while (abs(SensorValue[encoderright] / 2 + SensorValue[encoderright] / 2) < ticks) {
		motor[frontleft] = leftspeed;
		motor[backleft] = leftspeed;
		motor[frontright] = rightspeed;
		motor[backright] = rightspeed;

		lastError = error;

		error = SensorValue[encoderleft] - SensorValue[encoderright];

		derivative = error - lastError;

		rightspeed = speed + (error * kp) + (derivative * kd);

		datalogDataGroupStart();
		datalogAddValue(0, error);
		datalogAddValue(1, rightspeed);
		datalogDataGroupEnd();

	}

	stopDrive();

	pause();
}

void moveForward(int ticks, int speed) {
	resetSensors();

	int error;
	int kp = 0;

	int leftpower = speed;
	int rightpower = leftpower;

	while (SensorValue[encoderleft] < ticks) {
		error = SensorValue[encoderleft] - SensorValue[encoderright];
		rightpower = leftpower + (kp * error);
		motor[frontright] = rightpower;
		motor[backright] = rightpower;
		motor[backleft] = leftpower;
		motor[frontleft] = leftpower;
	}
	stopDrive();
}

void turnRight(int degrees, int speed) {
	/*
	int ticks = degrees * 51 / 20;

	SensorValue[encoderright] = 0;

	while (abs(SensorValue[encoderright]) < ticks) {
		motor[frontleft] = speed;
		motor[frontright] = -speed;
		motor[backleft] = speed;
		motor[backright] = -speed;
	}

	stopDrive();
	pause();*/
	resetSensors();
	int degrees10 = degrees * 9.4;
	int error = 5;

	while (abs(SensorValue[gyro]) < degrees10 - 100) {
		motor[frontright] = -speed;
		motor[frontleft] = speed;
		motor[backright] = -speed;
		motor[backleft] = speed;
	}

	motor[frontright] = 5;
	motor[frontleft] = -5;
	motor[backright] = 5;
	motor[backleft] = -5;

	wait1Msec(50);

	while (abs(SensorValue[gyro]) < degrees10 - error) {
		motor[frontright] = speed * -0.6;
		motor[frontleft] = speed * 0.6;
		motor[backleft] = speed * 0.6;
		motor[backright] = speed * -0.6;
	}

	stopDrive();
	pause();
}

void turnLeft (int degrees, int speed) {
	/*
	SensorValue[gyro] = 0;
	while (abs(SensorValue[gyro]) < degrees * 10) {
		motor[frontleft] = -speed;
		motor[backleft] = -speed;
		motor[frontright] = speed;
		motor[backright] = speed;
	}

	stopDrive();
	pause();*/
	resetSensors();
	int degrees10 = degrees * 9.4;
	int error = 5;

	while (abs(SensorValue[gyro]) < degrees10 - 100) {
		motor[frontright] = speed;
		motor[frontleft] = -speed;
		motor[backright] = speed;
		motor[backleft] = -speed;
	}

	motor[frontright] = -5;
	motor[frontleft] = 5;
	motor[backright] = -5;
	motor[backleft] = 5;

	wait1Msec(50);

	while (abs(SensorValue[gyro]) < degrees10 - error) {
		motor[frontright] = speed * 0.6;
		motor[frontleft] = speed * -0.6;
		motor[backleft] = speed * -0.6;
		motor[backright] = speed * 0.6;
	}

	stopDrive();
	pause();
}

void arm(int ticks, long time) {
	if (SensorValue[pot] > ticks) {
		while (SensorValue[pot] > ticks) {
			motor[armleft] = 63;
			motor[armright] = 63;
		}
	} else if (SensorValue[pot] < ticks) {
		while (SensorValue[pot] < ticks) {
			motor[armleft] = -63;
			motor[armright] = -63;
		}
	}

	pause();
}

void flip(long time) {
	motor[claw] = 127;
	wait1Msec(time);
	motor[claw] = 0;
}

void shoot() {
	motor[shooter] = 127;
	wait1Msec(1400);
	motor[shooter] = 0;
}

/*
Autonomous information:
Turning: (90, 50)
Movement: 466 per square
Shooting: 2nd or 4th square
*/

task autonomous () {
	//shoot();
	moveBackward(1400, -127);
	moveForward(466, 127);
	turnLeft(90, 50);
	moveForward(600, 127);
}

task usercontrol() {
	while (0==0) {
		//Driving with Joysticks
		motor[frontleft] = vexRT[Ch3];
		motor[backleft] = vexRT[Ch3];
		motor[frontright] = vexRT[Ch2];
		motor[backright] = vexRT[Ch2];
/*
		if (vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0 && angle > 1940) {
			motor[armleft] = -127;
			motor[armright] = -127;     //Pressed right foward bumper lifts arm
		} else if (vexRT[Btn6D] == 1 && vexRT[Btn6U] == 0 && angle < 2440) {
			motor[armleft] = 127;
			motor[armright] = 127;     //Pressed right back bumper lowers arm
		} else if ((vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0) || (vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)) {
			motor[armleft] = 0;
			motor[armright] = 0;
		} else {
			motor[armright] = 0;
			motor[armleft] = 0;
		}
		*/
		if (vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0) {
			motor[armleft] = -127;
			motor[armright] = -127;     //Pressed right foward bumper lifts arm
		} else if (vexRT[Btn6D] == 1 && vexRT[Btn6U] == 0) {
			motor[armleft] = 127;
			motor[armright] = 127;     //Pressed right back bumper lowers arm
		} else if ((vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0) || (vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0)) {
			motor[armleft] = 0;
			motor[armright] = 0;
		} else {
			motor[armright] = 0;
			motor[armleft] = 0;
		}

		if (vexRT[Btn5U] == 1 && vexRT[Btn5D] == 0) {
			motor[claw] = 55;
		} else if (vexRT[Btn5D] == 1 && vexRT[Btn5U] == 0) {
			motor[claw] = -55;
		} else {
			motor[claw] = 0;
		}

		if (vexRT[Btn8U] == 1 && vexRT[Btn8D] == 0) {
			motor[shooter] = 127;
		} else if (vexRT[Btn8D] == 1 && vexRT[Btn8U] == 0) {
			motor[shooter] = -127;
		} else {
			motor[shooter] = 0;
		}

		if (vexRT[Btn7L] == 1 && vexRT[Btn7R] == 0) {
			turnLeft(90, 60);
		} else if (vexRT[Btn7R] == 1 && vexRT[Btn7L] == 0) {
			turnRight(90, 60);
		} else {

		}
	}
}
